CREATE DATABASE Boap;
GO

USE Boap; 
GO

CREATE TABLE SERVER_CONFIGURATION(
    ID varchar(50) NOT NULL,
    PREFIX varchar(50) NOT NULL,
)
GO

ALTER TABLE SERVER_CONFIGURATION
ADD CONSTRAINT PK_SERVER_CONFIGURATION PRIMARY KEY (ID);
GO


CREATE TABLE USER_WARNS(
    SERVER_ID varchar(50) NOT NULL,
    USER_ID varchar(50) NOT NULL,
    WARNS int NOT NULL,
)
GO

ALTER TABLE USER_WARNS
ADD CONSTRAINT UC_SERVERID_USERID PRIMARY KEY (SERVER_ID, USER_ID);
GO

GO